-d F:\Project\Sipeed\FPGA\Tang_Mega\Riscv-SoC\Project\SoC\impl\gwsynthesis\SoC.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst F:\Project\Sipeed\FPGA\Tang_Mega\Riscv-SoC\Project\SoC\src\SoC.cst
-cfg F:\Project\Sipeed\FPGA\Tang_Mega\Riscv-SoC\Project\SoC\impl\pnr\device.cfg
-sdc F:\Project\Sipeed\FPGA\Tang_Mega\Riscv-SoC\Project\SoC\src\SoC.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
